# Form implementation generated from reading ui file 'Camera.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(258, 379)
        Form.setStyleSheet("QToolButton {\n"
"    qproperty-alignment: AlignCenter;\n"
"    border: 1px solid #FF17365D;\n"
"    background-color: #226091;\n"
"    padding: 3px;\n"
"    color: #FFFFFF;\n"
"    font: 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    color: #f0b321;\n"
"}\n"
"\n"
"QToolButton:pressed,\n"
"QToolButtont:checked {\n"
"    color: #f0b321;\n"
"    background-color: #19466a;\n"
"    border: 2px solid #f0b321;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    qproperty-alignment: AlignCenter;\n"
"    border: 1px solid #FF17365D;\n"
"    color: #f0b321;\n"
"    background-color: #226091;\n"
"    border-radius: 3px;\n"
"    selection-background-color:#19466a;\n"
"    selection-color: #f0b321;\n"
"    font: 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QSpinBox::up-button { subcontrol-origin: content;  subcontrol-position: right;  width:20px; height: 20px; }\n"
"QSpinBox::down-button {subcontrol-origin: content; subcontrol-position: left;  width:20px; height: 20px; }\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leConnetionStr = QtWidgets.QLineEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leConnetionStr.sizePolicy().hasHeightForWidth())
        self.leConnetionStr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.leConnetionStr.setFont(font)
        self.leConnetionStr.setObjectName("leConnetionStr")
        self.horizontalLayout.addWidget(self.leConnetionStr)
        self.tbRun = QtWidgets.QToolButton(parent=Form)
        self.tbRun.setMinimumSize(QtCore.QSize(28, 28))
        self.tbRun.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tbRun.setFont(font)
        self.tbRun.setText("")
        self.tbRun.setIconSize(QtCore.QSize(36, 36))
        self.tbRun.setCheckable(True)
        self.tbRun.setChecked(False)
        self.tbRun.setObjectName("tbRun")
        self.horizontalLayout.addWidget(self.tbRun)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbxAddGrade_2 = QtWidgets.QCheckBox(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.cbxAddGrade_2.setFont(font)
        self.cbxAddGrade_2.setObjectName("cbxAddGrade_2")
        self.horizontalLayout_3.addWidget(self.cbxAddGrade_2)
        self.spAmount = QtWidgets.QSpinBox(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spAmount.sizePolicy().hasHeightForWidth())
        self.spAmount.setSizePolicy(sizePolicy)
        self.spAmount.setMinimumSize(QtCore.QSize(100, 0))
        self.spAmount.setWrapping(False)
        self.spAmount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spAmount.setReadOnly(False)
        self.spAmount.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spAmount.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spAmount.setProperty("showGroupSeparator", True)
        self.spAmount.setMinimum(0)
        self.spAmount.setMaximum(100)
        self.spAmount.setProperty("value", 0)
        self.spAmount.setObjectName("spAmount")
        self.horizontalLayout_3.addWidget(self.spAmount)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbxAddGrade_3 = QtWidgets.QCheckBox(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.cbxAddGrade_3.setFont(font)
        self.cbxAddGrade_3.setObjectName("cbxAddGrade_3")
        self.horizontalLayout_4.addWidget(self.cbxAddGrade_3)
        self.spAmount_2 = QtWidgets.QSpinBox(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spAmount_2.sizePolicy().hasHeightForWidth())
        self.spAmount_2.setSizePolicy(sizePolicy)
        self.spAmount_2.setMinimumSize(QtCore.QSize(100, 0))
        self.spAmount_2.setWrapping(False)
        self.spAmount_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spAmount_2.setReadOnly(False)
        self.spAmount_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spAmount_2.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spAmount_2.setProperty("showGroupSeparator", True)
        self.spAmount_2.setMinimum(0)
        self.spAmount_2.setMaximum(100)
        self.spAmount_2.setProperty("value", 0)
        self.spAmount_2.setObjectName("spAmount_2")
        self.horizontalLayout_4.addWidget(self.spAmount_2)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frmGrade = QtWidgets.QFrame(parent=Form)
        self.frmGrade.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmGrade.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmGrade.setObjectName("frmGrade")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmGrade)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbxAddGrade = QtWidgets.QCheckBox(parent=self.frmGrade)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.cbxAddGrade.setFont(font)
        self.cbxAddGrade.setObjectName("cbxAddGrade")
        self.horizontalLayout_2.addWidget(self.cbxAddGrade)
        self.spGradeErrorPercent = QtWidgets.QSpinBox(parent=self.frmGrade)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spGradeErrorPercent.sizePolicy().hasHeightForWidth())
        self.spGradeErrorPercent.setSizePolicy(sizePolicy)
        self.spGradeErrorPercent.setMinimumSize(QtCore.QSize(100, 0))
        self.spGradeErrorPercent.setWrapping(False)
        self.spGradeErrorPercent.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spGradeErrorPercent.setReadOnly(False)
        self.spGradeErrorPercent.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spGradeErrorPercent.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spGradeErrorPercent.setProperty("showGroupSeparator", True)
        self.spGradeErrorPercent.setMinimum(0)
        self.spGradeErrorPercent.setMaximum(100)
        self.spGradeErrorPercent.setProperty("value", 0)
        self.spGradeErrorPercent.setObjectName("spGradeErrorPercent")
        self.horizontalLayout_2.addWidget(self.spGradeErrorPercent)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frmGrade)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.leName = QtWidgets.QLineEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leName.sizePolicy().hasHeightForWidth())
        self.leName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.leName.setFont(font)
        self.leName.setMaxLength(25)
        self.leName.setObjectName("leName")
        self.horizontalLayout_5.addWidget(self.leName)
        self.tbDel = QtWidgets.QToolButton(parent=Form)
        self.tbDel.setMinimumSize(QtCore.QSize(28, 28))
        self.tbDel.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tbDel.setFont(font)
        self.tbDel.setText("")
        self.tbDel.setIconSize(QtCore.QSize(36, 36))
        self.tbDel.setCheckable(False)
        self.tbDel.setChecked(False)
        self.tbDel.setObjectName("tbDel")
        self.horizontalLayout_5.addWidget(self.tbDel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.lstData = QtWidgets.QListView(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        self.lstData.setFont(font)
        self.lstData.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.lstData.setDragEnabled(True)
        self.lstData.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.DragDrop)
        self.lstData.setDefaultDropAction(QtCore.Qt.DropAction.TargetMoveAction)
        self.lstData.setAlternatingRowColors(True)
        self.lstData.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.lstData.setSelectionRectVisible(True)
        self.lstData.setObjectName("lstData")
        self.verticalLayout.addWidget(self.lstData)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.leConnetionStr.setPlaceholderText(_translate("Form", "Порт прослушивания (9100, например)"))
        self.cbxAddGrade_2.setText(_translate("Form", "NO READ"))
        self.spAmount.setSuffix(_translate("Form", " %"))
        self.cbxAddGrade_3.setText(_translate("Form", "DUPLICATE"))
        self.spAmount_2.setSuffix(_translate("Form", " %"))
        self.cbxAddGrade.setText(_translate("Form", "GRADE"))
        self.spGradeErrorPercent.setSuffix(_translate("Form", " %"))
        self.leName.setPlaceholderText(_translate("Form", "Название устройства"))
